
name: E2E tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install gcc-multilib
      run: |
        sudo apt-get clean && sudo apt-get update && sudo apt-get install gcc-multilib -y
    - name: run E2E test
      run: |
        cd tests/e2e_tests
        python3 e2e_test.py
